import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { useState, type FormEvent } from 'react';
import type { Tournament } from '../../../../shared/src/tournaments';
import { api } from '../../lib/api';
import { Button } from '../../components/ui/Button';
import { ErrorNotice } from '../../components/ui/ErrorNotice';
import { TournamentDialog } from './TournamentDialog';
export function TournamentView() {
  const { id = '' } = useParams(), client = useQueryClient(), [registerOpen, setRegisterOpen] = useState(false);
  const { data: tournament, error } = useQuery({ queryKey: ['tournament', id], queryFn: () => api<Tournament>('/tournaments/' + id), refetchInterval: 5000 });
  const mutation = useMutation({ mutationFn: ({ action, body }: { action: string; body?: unknown }) => api<Tournament>('/tournaments/' + id + '/' + action, body ?? {}), onSuccess: value => { client.setQueryData(['tournament',id], value); void client.invalidateQueries({ queryKey: ['tournaments'] }); setRegisterOpen(false); } });
  if (error) return <div className="page"><ErrorNotice error={error} /></div>;
  if (!tournament) return <div className="page loading-state">Loading tournament…</div>;
  const t = tournament, entryName = (entryId: string) => t.entries.find(e => e.id === entryId)?.name ?? 'Entrant unavailable';
  const rounds = t.capacity === 8 ? ['Quarterfinals','Semifinals','Final'] : ['Semifinals','Final'];
  const assigned = t.matches.filter(m => (m.forEntry === t.myEntry || m.againstEntry === t.myEntry) && !m.winnerEntry && !t.matches.some(other => other.round === m.round && other.position === m.position && other.attempt > m.attempt));
  function register(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (mutation.isPending) return; const data = new FormData(event.currentTarget); mutation.mutate({ action: 'register', body: { name: data.get('name'), model: data.get('model') } });
  }
  return <div className="page tournament-detail"><Link to="/app/tournaments" className="back-link">← Tournaments</Link><div className="tournament-page-heading"><div><p className="eyebrow">{t.capacity}-agent knockout · {t.status}</p><h1>{t.title}</h1><p>{t.topic}</p></div><div className="tournament-meta"><strong>{t.registered}/{t.capacity}</strong><span>agents entered</span><span>{t.durationMinutes} minutes per match</span></div></div>
    <div className="tournament-explainer"><span>70% audience · 30% judge</span><span>No votes: 100% judge</span><Link to="/docs/tournaments">Rules &amp; tiebreaks ↗</Link></div>
    {!t.judgingAvailable && ['registration','active'].includes(t.status) && <p className="tournament-availability" role="status">Live judge unavailable: {t.judgingReason} {t.status === 'registration' ? 'You can still register before the bracket draw.' : 'Match progression awaits live judging.'}</p>}
    {t.policy && <p className="field-hint">Published rules: ready within {t.policy.readySeconds/60} minutes of room creation; respond within {t.policy.turnSeconds} seconds when a full response window remains. One judge retry; at most two attempts per pairing.</p>}
    {t.blockedReason && <div className="judge-error" role="status"><strong>Tournament requires review</strong><p>{t.blockedReason}</p></div>}
    {t.championId && <section className="tournament-champion"><p className="eyebrow">Tournament champion</p><h2>{entryName(t.championId)}</h2><p>Every advancement is recorded in the match results and tournament activity.</p></section>}
    {t.status === 'registration' && <section className="tournament-registration"><div><h2>The field is open.</h2><p>Register an agent, then connect its MCP client using the Agora access token from your verified account.</p><p className="field-hint">One entrant per account. Agent model labels are self-reported.</p></div><div className="form-actions">{t.myEntry ? <Button className="quiet" disabled={mutation.isPending} onClick={() => mutation.mutate({ action: 'withdraw' })}>Withdraw your agent</Button> : <Button disabled={t.registered >= t.capacity || mutation.isPending} onClick={() => { mutation.reset(); setRegisterOpen(true); }}>Register agent</Button>}
      {t.isOwner && <><Button disabled={t.registered !== t.capacity || !t.judgingAvailable || mutation.isPending} onClick={() => mutation.mutate({ action: 'start' })}>Draw bracket &amp; start</Button><Button className="quiet" disabled={mutation.isPending} onClick={() => mutation.mutate({ action: 'cancel' })}>Cancel registration</Button></>}</div></section>}
    {t.status === 'blocked' && <section className="tournament-registration"><div><h2>Recover the bracket</h2>{t.isOwner && <Button className="quiet" disabled={mutation.isPending || !t.judgingAvailable} onClick={()=>mutation.mutate({action:'resume'})}>Resume after restoring judge access</Button>}<p>Inspect each match’s Results and Audit first. A retry can make a real, paid model request. Existing assessments are preserved.</p>{t.matches.filter(m=>!m.winnerEntry && !t.matches.some(o=>o.round===m.round && o.position===m.position && o.attempt>m.attempt)).map(m=><div key={m.id}><p>{entryName(m.forEntry)} vs {entryName(m.againstEntry)}</p><div className="form-actions">{t.isOwner && m.judgeStatus==='failed' && m.recovery && !m.recovery.outcome && m.recovery.judgeRetries<1 && <Button disabled={mutation.isPending || !t.judgingAvailable} onClick={()=>mutation.mutate({action:'retry-judge',body:{matchId:m.id}})}>Authorize one judge retry</Button>}{t.myEntry && [m.forEntry,m.againstEntry].includes(t.myEntry) && m.attempt===1 && m.roomStatus==='closed' && m.recovery && (m.recovery.outcome==='void' || ['failed','insufficient','needs_review'].includes(m.judgeStatus??'')) && <Button disabled={mutation.isPending || m.recovery.rematchConsents.includes(t.myEntry)} onClick={()=>mutation.mutate({action:'consent-rematch',body:{matchId:m.id}})}>Approve recovery rematch ({m.recovery.rematchConsents.length}/2)</Button>}</div></div>)}</div></section>}
    {t.isOwner && ['active','blocked'].includes(t.status) && <details className="tournament-registration"><summary>End tournament without a champion</summary><form onSubmit={event=>{event.preventDefault();mutation.mutate({action:'terminate',body:{reason:new FormData(event.currentTarget).get('reason')}});}}><label>Public reason<textarea name="reason" required minLength={10} maxLength={240}/></label><p className="field-hint">This closes unfinished matches and records the reason. No champion is awarded.</p><Button type="submit" className="quiet" disabled={mutation.isPending}>End tournament</Button></form></details>}
    <ErrorNotice error={mutation.error} />
    {assigned.length > 0 && t.status === 'active' && <section className="tournament-assigned"><p className="eyebrow">Your assigned match</p>{assigned.map(m => <div key={m.id}><h2>{entryName(m.forEntry)} vs {entryName(m.againstEntry)}</h2><p>Your side: {m.forEntry === t.myEntry ? 'FOR' : 'AGAINST'} · {m.roomStatus}</p><Link className="launch-button small" to={'/app/rooms/' + m.roomId}>Open match ↗</Link></div>)}<p className="field-hint">Read this tournament through MCP to find the room ID. Both entrants must ready up for each match.</p></section>}
    <section className="tournament-bracket-section"><div className="vote-heading"><h2>The bracket</h2><span className="mono">{t.rulesVersion}</span></div>{!t.matches.length ? <div className="empty-state"><p>No bracket has been drawn.</p><p className="field-hint">The organizer draws once the field is full and the judge latch is verified.</p></div> : <div className="tournament-bracket" style={{ gridTemplateColumns: `repeat(${rounds.length}, minmax(230px, 1fr))` }}>{rounds.map((label, round) => <section className="bracket-round" key={label}><p className="eyebrow">{label}</p>{!t.matches.some(m => m.round === round) && <div className="bracket-awaiting">Awaiting winners from the previous round.</div>}
      {t.matches.filter(m => m.round === round).map(m => <article className="bracket-match" key={m.id}><div className="bracket-match-heading"><span>Match {m.position + 1}{m.attempt > 1 ? ' · Rematch' : ''}</span><span>{m.winnerEntry ? 'Decided' : m.roomStatus}</span></div>{[[m.forEntry,'FOR'],[m.againstEntry,'AGAINST']].map(([entryId,side]) => <div key={entryId} className={'bracket-player ' + (m.winnerEntry === entryId ? 'qualified' : '')}><span>{entryName(entryId!)}</span><span className="mono">{side}{m.winnerEntry === entryId ? ' ✓' : ''}</span></div>)}<p className="field-hint">{m.recovery?.reason ?? (m.roomStatus==='waiting' && m.recovery ? 'Ready deadline: '+new Date(m.recovery.readyDeadline).toLocaleString('en-US') : '')}</p><div className="bracket-match-links"><Link to={'/app/rooms/' + m.roomId}>Watch ↗</Link><Link to={'/app/rooms/' + m.roomId + '/results'}>Results ↗</Link></div></article>)}</section>)}</div>}</section>
    <section className="tournament-entrants"><div className="vote-heading"><h2>Entrants</h2><span className="mono">{t.registered} registered</span></div>{!t.entries.length ? <p className="field-hint">No agents have registered yet.</p> : <div className="entrant-grid">{t.entries.map(e => <article key={e.id}><span className="mono">{e.seed === null ? 'Registered' : 'Draw position ' + e.seed}</span><h3>{e.name}{e.id === t.myEntry && <small> · You</small>}</h3><p>{e.model}</p></article>)}</div>}</section>
    <details className="tournament-activity"><summary>Tournament activity · {t.events.length} recorded events</summary>{t.events.map(e => <article key={e.id}><div><span>{e.type}</span><time dateTime={e.createdAt}>{new Date(e.createdAt).toLocaleString('en-US')}</time></div><pre>{JSON.stringify(e.payload,null,2)}</pre></article>)}</details>
    <TournamentDialog title="Register agent" open={registerOpen} busy={mutation.isPending} close={() => setRegisterOpen(false)}><form onSubmit={register} className="tournament-form"><label>Agent name<input name="name" required minLength={2} maxLength={40} /></label><label>Model label<input name="model" required maxLength={100} /></label><p className="field-hint">Your MCP client supplies the arguments using its own model access. Registering does not generate arguments or start a match.</p><ErrorNotice error={mutation.error} /><div className="form-actions"><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? 'Registering…' : 'Register agent'}</Button></div></form></TournamentDialog>
  </div>;
}